easy_admin:
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y h:i A e'
    entities:
        # List the entity class name you want to manage
        Stage:
          class: 'App\Entity\Stage'
          list:
              fields: ['numero_stage', 'debut_de_stage', 'fin_de_stage', 'animateur', 'animateur_deux', 'stage_hpo', 'lieux_de_stage', 'stagiaires', 'alert']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - { property: 'numero_stage', type: 'text' }
                  - { property: 'debut_de_stage', type: 'date' }
                  - { property: 'fin_de_stage', type: 'date' }
                  - { property: 'animateur', class: 'App\Entity\Animateur' }
                  - { property: 'animateur_deux', class: 'App\Entity\Animateur' }
                  - { property: 'stage_hpo' }
                  - { property: 'lieux_de_stage', class: 'App\Entity\Lieux_de_stage' }
                  - { type: 'group', css_class: 'col-sm-6', label: 'Urgent', icon: 'bell' }
                  - { property: 'alert' }

        Stagiaire:
          class: 'App\Entity\Stagiaire'
          list:
              fields: ['date_de_creation', 'genre', 'nom', 'nom_epouse', 'prenom', 'date_de_naissance', 'lieu_de_naissance', 'pays', 'adresse', 'code_postal', 'commune', 'numero_telephone_fixe', 'numero_telephone_portable', 'numero_telephone_portable_deux', 'adresse_email', 'carte_avantage_jeunes', 'partenaires', 'adherents', 'cas', 'infractions', 'prix', 'stages']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - { property: 'date_de_creation', type: 'text'}
                  - { property: 'genre', type: 'text' }
                  - { property: 'nom', type: 'text' }
                  - { property: 'nom_epouse', type: 'text' }
                  - { property: 'prenom', type: 'text' }
                  - { property: 'date_de_naissance', type: 'birthday' }
                  - { property: 'lieu_de_naissance', type: 'text' }
                  - { property: 'pays', type: 'text' }
                  - { type: 'group', css_class: 'col-sm-6', label: 'Adresse', icon: 'location-arrow' }
                  - { property: 'adresse', type: 'text' }
                  - { property: 'code_postal', type: 'text' }
                  - { property: 'commune', type: 'text' }
                  - { type: 'group', label: 'Contact', icon: 'phone',
                        css_class: 'col-sm-6' }
                  - { property: 'numero_telephone_fixe', type: 'text' }
                  - { property: 'numero_telephone_portable', type: 'text' }
                  - { property: 'numero_telephone_portable_deux', type: 'text' }
                  - { property: 'adresse_email', type: 'text' }
                  - { type: 'group', css_class: 'col-sm-6', label: 'Administration', icon: 'book' }
                  - { property: 'carte_avantage_jeunes' }
                  - { property: 'partenaires' }
                  - { property: 'adherents' }
                  - { property: 'cas', class: 'App\Entity\Cas' }
                  - { property: 'prix', type: 'text'}
                  
        Infraction:
          class: 'App\Entity\Infraction'
          list:
              fields: ['lieu', 'date_infraction', 'heure', 'date_tribunal', 'cs_permis', 'cs_assurance', 'stagiaires', 'tribunaux', 'types_infractions']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - { property: 'lieu', type: 'text' }
                  - { property: 'date_infraction', type: 'date' }
                  - { property: 'heure', type: 'time' }
                  - { property: 'date_tribunal', type: 'date' }
                  - { property: 'cs_permis', type: 'text' }
                  - { property: 'cs_assurance', type: 'text' }
                  - { property: 'stagiaires', class: 'App\Entity\Stagiaire' }
                  - { property: 'tribunaux', class: 'App\Entity\Tribunal' }
                  - { property: 'types_infractions', class: 'App\Entity\Type_infraction' }

        Permis:
          class: 'App\Entity\Permis'
          list:
            fields: ['stagiaires', 'permis', 'delivre_le', 'prefectures']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - { property: 'stagiaires', class: 'App\Entity\Stagiaire' }
                  - { property: 'permis', type: 'text'}
                  - { property: 'delivre_le', type: 'birthday' }
                  - { property: 'prefectures', class: 'App\Entity\Prefecture' }
                  
        Bordereau:
          class: 'App\Entity\Bordereau'
          list:
            fields: ['autorite', 'etablissement', 'adresse', 'code_postal', 'ville', 'prefectures', 'tribunaux', 'stagiaires_stages']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - autorite
                  - etablissement
                  - adresse
                  - code_postal
                  - ville
                  - prefectures
                  - tribunaux

        Stagiaire_Stage:
          class: 'App\Entity\Stagiaire_Stage'
          list:
              fields: ['stagiaires', 'stages', 'paye', 'prix', 'cas', 'bordereaux', 'envoi_inscription', 'envoi_convocation', 'courrier', 'email', 'bulletin_inscription', 'cni', 'copie_permis', 'releve_integral', 'decision_judiciaire', 'n48', 'observations']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - stagiaires
                  - stages
                  - paye
                  - prix
                  - cas
                  - { type: 'group', css_class: 'col-sm-6', label: 'Administration', icon: 'book' }
                  - bordereaux
                  - envoi_inscription
                  - envoi_convocation
                  - courrier
                  - email
                  - bulletin_inscription
                  - cni
                  - copie_permis
                  - releve_integral
                  - decision_judiciaire
                  - n48
                  - observations

        Animateur:
          class: 'App\Entity\Animateur'
          list:
              fields: ['civilite', 'nom', 'prenom', 'fonctions', 'statut', 'gta', 'raison_sociale', 'adresse', 'code_postal', 'ville', 'region', 'numero_telephone_fixe', 'numero_telephone_portable', 'adresse_email', 'urssaf', 'siret', 'forfait', 'km_ar', 'repas']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - civilite
                  - nom
                  - prenom
                  - fonctions
                  - statut
                  - gta
                  - raison_sociale
                  - { type: 'group', css_class: 'col-sm-6', label: 'Adresse', icon: 'location-arrow' }
                  - adresse
                  - code_postal
                  - ville
                  - region
                  - { type: 'group', label: 'Contact information', icon: 'phone',
                        css_class: 'col-sm-6' }
                  - numero_telephone_fixe
                  - numero_telephone_portable
                  - adresse_email
                  - { type: 'group', css_class: 'col-sm-6', label: 'Administration', icon: 'book' }
                  - urssaf
                  - siret
                  - forfait
                  - km_ar
                  - repas
                  
        Fonction:
          class: 'App\Entity\Fonction'
          list:
            fields: ['fonction']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - fonction

        Lieux_de_stage:
          class: 'App\Entity\Lieux_de_stage'
          list:
            fields: ['lieux', 'organisme', 'adresse', 'code_postal', 'ville', 'numero_telephone_fixe', 'latitude', 'longitude', 'divers']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - lieux
                  - organisme
                  - { type: 'group', css_class: 'col-sm-6', label: 'Adresse', icon: 'location-arrow' }
                  - adresse
                  - code_postal
                  - ville
                  - { type: 'group', label: 'Contact information', icon: 'phone',
                        css_class: 'col-sm-6' }
                  - numero_telephone_fixe
                  - { type: 'group', css_class: 'col-sm-6', label: 'Coordonnées' }
                  - latitude
                  - longitude
                  - { type: 'group', css_class: 'col-sm-6', label: 'Autres' }
                  - divers

        Tribunal:
          class: 'App\Entity\Tribunal'
          list:
            fields: ['tribunal', 'numero_parquet']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - tribunal
                  - numero_parquet

        Prefecture:
          class: 'App\Entity\Prefecture'
          list:
            fields: ['prefecture', 'permis']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - prefecture

        Type_infraction:
          class: 'App\Entity\Type_infraction'
          list:
            fields: ['types_infractions']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - types_infractions

        Cas:
          class: 'App\Entity\Cas'
          list:
            fields: ['cas', 'description']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - cas
                  - description

        Admin:
          class: 'App\Entity\Admin'
          list:
              fields: ['pseudo', 'adresse_email', 'password']
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-6', label: 'Information', icon: 'info-circle' }
                  - pseudo
                  - adresse_email
                  - password

    site_name: "Afer"

    design:
        form_theme: 'vertical'
        menu: 
            - { entity: 'Stage', icon: 'users' }
            - { entity: 'Stagiaire', icon: 'user' }
            - { entity: 'Infraction', icon: 'car' }
            - { entity: 'Permis', icon: 'id-card' }
            - { entity: 'Bordereau', icon: 'paper-plane' }
            - { entity: 'Stagiaire_Stage', icon: 'users' }
            - { entity: 'Animateur', icon: ' ' }
            - { entity: 'Fonction', icon: ' ' }
            - { entity: 'Lieux_de_stage', icon: ' ' }
            - { entity: 'Tribunal', icon: ' ' }
            - { entity: 'Prefecture', icon: ' ' }
            - { entity: 'Type_infraction', icon: ' ' }
            - { entity: 'Cas', icon: ' ' }
            - { entity: 'Admin', icon: ' ' }
        assets:
            favicon:
                path: 'backend/favicon.png'